package datasource;

import domain.AudioCodec;
import domain.Cost;
import domain.VideoStreaming;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.function.Function;

public class ProductGateway {

    private long id;
    private ProductType type;
    private String sku;
    private String name;
    private double basePrice;
    private long size;
    private boolean hasLyrics;
    private Set<AudioCodec> codecs;
    private boolean hasSubtitles;
    private int videoResolution;
    private ArrayList<VideoStreaming> supportedStreamingServices;

    //========================================================================================================
    // This is where the table driven gateway's static methods should go
    //========================================================================================================
    public static List<ProductGateway> findAllRows() {
        return null;
    }

    public long getId() {
        return id;
    }

    public ProductType getType() {
        return type;
    }

    public String getSku() {
        return sku;
    }

    public String getName() {
        return name;
    }

    public double getBasePrice() {
        return basePrice;
    }

    public long getSize() {
        return size;
    }

    public boolean isHasLyrics() {
        return hasLyrics;
    }

    public Set<AudioCodec> getCodecs() {
        return codecs;
    }

    public boolean isHasSubtitles() {
        return hasSubtitles;
    }

    public int getVideoResolution() {
        return videoResolution;
    }

    public ArrayList<VideoStreaming> getSupportedStreamingServices() {
        return supportedStreamingServices;
    }

    /**
     * Create constructor - used to put a new object into the db
     * @param type
     * @param sku
     * @param name
     * @param basePrice
     * @param size
     * @param hasLyrics
     * @param codecs
     * @param supportedStreamingServices
     */
    public ProductGateway(ProductType type, String sku, String name, double basePrice,
                          long size, boolean hasLyrics, Set<AudioCodec> codecs, ArrayList<VideoStreaming> supportedStreamingServices) {
        this.type = type;
        this.sku = sku;
        this.name = name;
        this.basePrice = basePrice;
        this.size = size;
        this.hasLyrics = hasLyrics;
        this.codecs = codecs;
        this.supportedStreamingServices = supportedStreamingServices;

        String url = "jdbc:sqlite:Gateway.sqlite";
        try (Connection conn = DriverManager.getConnection(url)) {
            if (conn != null) {

                String sql = "INSERT INTO ProductGateway "
                            + "(sku, name, basePrice, size, hasLyrics, codecs, type)"
                            + "VALUES (?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement insert = conn.prepareStatement(sql);
                insert.setString(1, sku);
                insert.setString(2, name);
                insert.setDouble(3, basePrice);
                insert.setLong(4, size);
                insert.setBoolean(5, hasLyrics);
                insert.setInt(6, calculateBitmask(codecs));
                insert.setInt(7, type.ordinal());

                insert.execute();
                insert.close();

                // TODO set the id with the one generated by the INSERT
                /// The current issue with this is the potential for race conditions
                /// look more into different options of doing this
                PreparedStatement stmt = conn.prepareStatement("SELECT MAX(id) AS maxID FROM ProductGateway");
                ResultSet set = stmt.executeQuery();
                //TODO - Does this need to close? What if we put insert.close() after this?
                set.next();
                id = set.getInt("maxID");

                if(type == ProductType.Electronics){
                    insertSupportedServices(conn);
                }

            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }

        // TODO now you have to store the many to many relationship
    }

    public void insertSupportedServices(Connection connection) throws SQLException {
        //Separate Table necessary for many-to-many relationship
        String supportedServiceSql = "INSERT INTO SupportedServices (ElectronicsID, VideoStreamingID) VALUES (?, ?)";
        PreparedStatement insertService = connection.prepareStatement(supportedServiceSql);
        for(VideoStreaming service : supportedStreamingServices){
            insertService.setLong(1, this.getId());
            insertService.setLong(2, service.getId());
            insertService.executeUpdate();
        }
    }

    /**
     * A finder constructor that will be used by findAndBuild only
     * @param id
     */
    private ProductGateway(long id) {
        String url = "jdbc:sqlite:Gateway.sqlite";
        this.id = id;
        try (Connection conn = DriverManager.getConnection(url)) {
            if (conn != null) {
                // TODO build the right select statement
                String sql = "SELECT * FROM ProductGateway "
                           + "Where id = ?";
                PreparedStatement select = conn.prepareStatement(sql);
                select.setLong(1, id);

                // TODO fill all of the instance variables from that select statement
                select.execute();
                select.close();
                /*
                if rs.hasNext
                getDataOutOfResultSet.set
                 */
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public static <T> T findAndBuild(long id, Function<ProductGateway, T> domainBuilder) {
        ProductGateway gateway = new ProductGateway(id);
        return domainBuilder.apply(gateway);
    }

    private Set<AudioCodec> getSupportedCodecsSet(int mask) {
        Set<AudioCodec> codecs = new java.util.HashSet<>();
        for (AudioCodec codec : AudioCodec.values()) {
            int shift = 1 << codec.ordinal();
            if ((mask & shift) != 0) {
                codecs.add(codec);
            }
        }
        return codecs;
    }

    private int calculateBitmask(Set<AudioCodec> codecs) {
        int bitmask = 0;
        for (AudioCodec codec : codecs) {
            // ordinal takes the specific placement of codec in the enum
            // (so that it registers the different types)
            bitmask |= (1 << codec.ordinal());
        }
        return bitmask;
    }
}
